'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Signal, SignalDetail } from '../types/strategy'
import { fetchSignals, fetchSignal } from '../lib/api'

export default function SignalsPage() {
  const [signals, setSignals] = useState<Signal[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [filter, setFilter] = useState<{ side?: string; symbol?: string }>({})
  const [selectedSignal, setSelectedSignal] = useState<SignalDetail | null>(null)

  const loadSignals = async () => {
    try {
      setLoading(true)
      const data = await fetchSignals({ ...filter, limit: 100 })
      setSignals(data)
      setError(null)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadSignals()
  }, [filter])

  const handleViewDetail = async (id: string) => {
    try {
      const data = await fetchSignal(id)
      setSelectedSignal(data)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load detail')
    }
  }

  return (
    <main className="min-h-screen p-8">
      <div className="max-w-6xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold text-white">Signals</h1>
            <p className="text-gray-400 text-sm">Trading signals generated by strategies</p>
          </div>
          <Link href="/" className="px-4 py-2 text-gray-400 hover:text-white transition">
            Back
          </Link>
        </div>

        <div className="flex gap-4 mb-6">
          <div className="flex gap-2">
            <button
              onClick={() => setFilter((f) => ({ ...f, side: undefined }))}
              className={`px-3 py-1 text-sm rounded ${
                !filter.side ? 'bg-blue-600 text-white' : 'bg-gray-700 text-gray-300'
              }`}
            >
              All Sides
            </button>
            <button
              onClick={() => setFilter((f) => ({ ...f, side: 'long' }))}
              className={`px-3 py-1 text-sm rounded ${
                filter.side === 'long' ? 'bg-green-600 text-white' : 'bg-gray-700 text-gray-300'
              }`}
            >
              Long
            </button>
            <button
              onClick={() => setFilter((f) => ({ ...f, side: 'short' }))}
              className={`px-3 py-1 text-sm rounded ${
                filter.side === 'short' ? 'bg-red-600 text-white' : 'bg-gray-700 text-gray-300'
              }`}
            >
              Short
            </button>
          </div>
          <input
            type="text"
            placeholder="Filter by symbol..."
            value={filter.symbol || ''}
            onChange={(e) => setFilter((f) => ({ ...f, symbol: e.target.value || undefined }))}
            className="px-3 py-1 bg-gray-800 border border-gray-700 rounded text-white text-sm"
          />
        </div>

        {error && (
          <div className="mb-4 p-3 bg-red-900/30 border border-red-700 rounded-lg text-red-300">
            {error}
          </div>
        )}

        <div className="grid gap-6 lg:grid-cols-3">
          <div className="lg:col-span-2">
            {loading ? (
              <div className="text-gray-400">Loading...</div>
            ) : signals.length === 0 ? (
              <div className="bg-gray-900 rounded-lg p-8 text-center">
                <p className="text-gray-400">No signals found</p>
              </div>
            ) : (
              <div className="bg-gray-900 rounded-lg overflow-hidden">
                <table className="w-full">
                  <thead className="bg-gray-800">
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase">Time</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase">Symbol</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase">Side</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase">TF</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase">Score</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase">Reason</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-800">
                    {signals.map((s) => (
                      <tr
                        key={s.id}
                        onClick={() => handleViewDetail(s.id)}
                        className="hover:bg-gray-800/50 cursor-pointer"
                      >
                        <td className="px-4 py-3 text-gray-300 text-sm">
                          {new Date(s.created_at).toLocaleString()}
                        </td>
                        <td className="px-4 py-3 text-white">{s.symbol}</td>
                        <td className="px-4 py-3">
                          <span
                            className={`px-2 py-0.5 text-xs rounded ${
                              s.side === 'long'
                                ? 'bg-green-900/50 text-green-400'
                                : 'bg-red-900/50 text-red-400'
                            }`}
                          >
                            {s.side.toUpperCase()}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-gray-300 text-sm">{s.timeframe}</td>
                        <td className="px-4 py-3 text-gray-300">{s.score}</td>
                        <td className="px-4 py-3 text-gray-400 text-sm truncate max-w-[200px]">
                          {s.reason_summary || '-'}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          <div>
            {selectedSignal ? (
              <div className="bg-gray-900 rounded-lg p-4 sticky top-8">
                <h3 className="text-lg font-semibold text-white mb-3">Signal Detail</h3>
                <dl className="space-y-2 text-sm">
                  <div>
                    <dt className="text-gray-400">Strategy</dt>
                    <dd className="text-gray-200">
                      <Link
                        href={`/strategies/${selectedSignal.strategy_id}`}
                        className="text-blue-400 hover:text-blue-300"
                      >
                        {selectedSignal.strategy_name || selectedSignal.strategy_id}
                      </Link>
                    </dd>
                  </div>
                  <div>
                    <dt className="text-gray-400">Symbol</dt>
                    <dd className="text-gray-200">{selectedSignal.symbol}</dd>
                  </div>
                  <div>
                    <dt className="text-gray-400">Side</dt>
                    <dd className={selectedSignal.side === 'long' ? 'text-green-400' : 'text-red-400'}>
                      {selectedSignal.side.toUpperCase()}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-gray-400">Time</dt>
                    <dd className="text-gray-200">
                      {new Date(selectedSignal.created_at).toLocaleString()}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-gray-400">Reason</dt>
                    <dd className="text-gray-200">{selectedSignal.reason_summary || '-'}</dd>
                  </div>
                </dl>

                {selectedSignal.indicators_at_signal && (
                  <div className="mt-4 pt-4 border-t border-gray-800">
                    <h4 className="text-sm font-medium text-gray-300 mb-2">Indicators at Signal</h4>
                    <dl className="space-y-1 text-sm">
                      {Object.entries(selectedSignal.indicators_at_signal).map(([name, value]) => (
                        <div key={name} className="flex justify-between">
                          <dt className="text-gray-400">{name}</dt>
                          <dd className="text-gray-200">
                            {value !== null ? Number(value).toFixed(4) : '-'}
                          </dd>
                        </div>
                      ))}
                    </dl>
                  </div>
                )}

                <button
                  onClick={() => setSelectedSignal(null)}
                  className="mt-4 text-gray-400 hover:text-white text-sm"
                >
                  Close
                </button>
              </div>
            ) : (
              <div className="bg-gray-900 rounded-lg p-4 text-gray-400 text-sm">
                Click a signal to view details
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  )
}
